# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosract718' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iosract718
  pod 'MobileCenter', '~> 0.10.1'
  pod 'RNMobileCenterShared', '~> 0.7.0'

  

  target 'iosract718Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'iosract718-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iosract718-tvOS

  target 'iosract718-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
